[package]
name = "goglogin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.3.1"
wry = "0.21.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3